#!/usr/bin/env python3
"""Convert JSON vocabulary data into SQL INSERT statements for data.sql.

Reads:
  - docs/references/ngsl-top1000.json  (1000 words)
  - docs/references/vocabulary.json    (19 vocabulary + 6 patterns)

Writes:
  - backend/src/main/resources/data.sql
"""

import json
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

NGSL_PATH = PROJECT_ROOT / "docs" / "references" / "ngsl-top1000.json"
VOCAB_PATH = PROJECT_ROOT / "docs" / "references" / "vocabulary.json"
OUTPUT_PATH = PROJECT_ROOT / "backend" / "src" / "main" / "resources" / "data.sql"

GRAMMAR_TOPICS = [
    (1, "受動態（Passive Voice）", "step1-grammar/01-passive-voice.md"),
    (2, "条件文（Conditionals）", "step1-grammar/02-conditionals.md"),
    (3, "関係代名詞（Relative Pronouns）", "step1-grammar/03-relative-pronouns.md"),
    (4, "不定詞・動名詞（Infinitives & Gerunds）", "step1-grammar/04-infinitives-gerunds.md"),
    (5, "比較表現（Comparatives）", "step1-grammar/05-comparatives.md"),
    (6, "コロン・セミコロン（Colons & Semicolons）", "step1-grammar/06-colons-semicolons.md"),
    (7, "使役・知覚構文（Causative & Perception）", "step1-grammar/07-causative-perception.md"),
    (8, "無生物主語（Inanimate Subject）", "step1-grammar/08-inanimate-subject.md"),
    (9, "後置修飾分詞（Post-modifying Participles）", "step1-grammar/09-post-modifying-participles.md"),
    (10, "同格のthat（Appositive That）", "step1-grammar/10-appositive-that.md"),
    (11, "with + O + C構文", "step1-grammar/11-with-opc.md"),
    (12, "分詞構文（Participial Constructions）", "step1-grammar/12-participial-constructions.md"),
    (13, "前置詞+関係代名詞", "step1-grammar/13-preposition-relative.md"),
    (14, "倒置・強調（Inversion & Emphasis）", "step1-grammar/14-inversion-emphasis.md"),
]


def escape_sql(value):
    """Escape a string value for SQL by doubling single quotes."""
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def strip_bold(text):
    """Remove **bold** markdown markers from text."""
    if text is None:
        return None
    return re.sub(r"\*\*(.+?)\*\*", r"\1", text)


def convert_ngsl(words):
    """Convert NGSL words to INSERT statements."""
    lines = []
    for w in words:
        word = escape_sql(w["word"])
        meaning_general = escape_sql(w["meanings"]["general"])
        meaning_it = escape_sql(w["meanings"].get("it"))
        frequency = w["rank"]
        lines.append(
            f"INSERT INTO words (word, meaning_general, meaning_it, frequency, source, level, known) "
            f"VALUES ({word}, {meaning_general}, {meaning_it}, {frequency}, 'NGSL', 1, 0);"
        )
    return lines


def convert_vocabulary(items):
    """Convert vocabulary.json entries (vocabulary + patterns) to INSERT statements."""
    lines = []
    for item in items:
        word = escape_sql(item["term"])
        meaning_general = escape_sql(item["meaning"])
        part_of_speech = escape_sql(item.get("partOfSpeech"))
        domain = escape_sql(item.get("domain"))
        source = escape_sql(item.get("source"))
        example_en = escape_sql(strip_bold(item.get("example")))
        example_ja = escape_sql(strip_bold(item.get("exampleJa")))
        lines.append(
            f"INSERT INTO words (word, meaning_general, part_of_speech, domain, source, example_en, example_ja, level, known) "
            f"VALUES ({word}, {meaning_general}, {part_of_speech}, {domain}, {source}, {example_en}, {example_ja}, 2, 0);"
        )
    return lines


def convert_grammar_topics():
    """Convert hardcoded grammar topics to INSERT statements."""
    lines = []
    for sort_order, title, doc_path in GRAMMAR_TOPICS:
        lines.append(
            f"INSERT INTO grammar_topics (sort_order, title, doc_path, completed) "
            f"VALUES ({sort_order}, {escape_sql(title)}, {escape_sql(doc_path)}, 0);"
        )
    return lines


def main():
    # Load NGSL data
    with open(NGSL_PATH, encoding="utf-8") as f:
        ngsl_data = json.load(f)

    # Load vocabulary data
    with open(VOCAB_PATH, encoding="utf-8") as f:
        vocab_data = json.load(f)

    ngsl_lines = convert_ngsl(ngsl_data["words"])
    vocab_lines = convert_vocabulary(vocab_data["vocabulary"] + vocab_data["patterns"])
    grammar_lines = convert_grammar_topics()

    output_lines = [
        "-- Auto-generated by scripts/migrate-json-to-sql.py",
        "-- Do not edit manually.",
        "",
        "-- Clear existing data to allow re-runs on restart",
        "DELETE FROM words;",
        "DELETE FROM grammar_topics;",
        "",
        "-- NGSL top 1000 words",
    ]
    output_lines.extend(ngsl_lines)
    output_lines.append("")
    output_lines.append("-- Vocabulary from vocabulary.json (words + patterns)")
    output_lines.extend(vocab_lines)
    output_lines.append("")
    output_lines.append("-- Grammar topics")
    output_lines.extend(grammar_lines)
    output_lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(output_lines))

    print(f"Generated {OUTPUT_PATH}")
    print(f"  NGSL words:       {len(ngsl_lines)}")
    print(f"  Vocabulary items: {len(vocab_lines)}")
    print(f"  Grammar topics:   {len(grammar_lines)}")
    print(f"  Total words:      {len(ngsl_lines) + len(vocab_lines)}")


if __name__ == "__main__":
    main()
